load("@grpc//bazel:cc_grpc_library.bzl", "cc_grpc_library")
load("@protobuf//bazel:cc_proto_library.bzl", "cc_proto_library")
load("@protobuf//bazel:proto_library.bzl", "proto_library")
load("//cuttlefish/bazel:rules.bzl", "cf_cc_binary", "cf_cc_library", "cf_cc_test")

package(
    default_visibility = ["//:android_cuttlefish"],
)

proto_library(
    name = "virtual_tuner_proto",
    srcs = ["VirtualTuner.proto"],
)

cc_proto_library(
    name = "virtual_tuner_cc_proto",
    deps = [":virtual_tuner_proto"],
)

cc_grpc_library(
    name = "libcvd_virtual_tuner",
    srcs = [":virtual_tuner_proto"],
    grpc_only = True,
    deps = [
        ":virtual_tuner_cc_proto",
        "@grpc//:grpc++",
    ],
)

cf_cc_library(
    name = "virtual_tuner_core",
    srcs = [
        "audio_generator.cpp",
        "pcm_stream_server.cpp",
        "tuner_state.cpp",
        "virtual_tuner_service.cpp",
    ],
    hdrs = [
        "audio_generator.h",
        "pcm_stream_server.h",
        "tuner_state.h",
        "virtual_tuner_service.h",
    ],
    depend_on_what_you_use_enabled = False,
    include_cleaner_enabled = False,
    deps = [
        ":libcvd_virtual_tuner",
        ":virtual_tuner_cc_proto",
        "//cuttlefish/common/libs/fs",
        "//cuttlefish/common/libs/fs:unique_fd",
        "//cuttlefish/result",
        "//libbase",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/strings",
        "@grpc//:grpc++",
    ],
)

cf_cc_binary(
    name = "virtual_tuner_daemon",
    srcs = [
        "main.cpp",
    ],
    depend_on_what_you_use_enabled = False,
    include_cleaner_enabled = False,
    deps = [
        ":virtual_tuner_core",
        "//cuttlefish/flag_parser",
        "//cuttlefish/host/libs/config:logging",
        "@abseil-cpp//absl/log",
        "@grpc//:grpc++",
        "@grpc//:grpc++_reflection",
    ],
)

cf_cc_test(
    name = "virtual_tuner_daemon_test",
    srcs = [
        "virtual_tuner_daemon_test.cpp",
    ],
    depend_on_what_you_use_enabled = False,
    include_cleaner_enabled = False,
    deps = [
        ":libcvd_virtual_tuner",
        ":virtual_tuner_cc_proto",
        ":virtual_tuner_core",
        "//cuttlefish/common/libs/fs",
        "//cuttlefish/common/libs/fs:unique_fd",
        "@grpc//:grpc++",
    ],
)
